### ISSUE TITLE
auto-generating gmail filters 

### ISSUE THREAD

**Issue by kmahar** [haystack/murmur#110]
We want something that can take in a list of email addresses, key words, etc. and generate the correct XML for gmail to use to forward emails on to Squadbox based on meeting or not meeting those criteria. Then we can use this for people who have Squadbox moderate emails sent to their Gmail account.

**Comment by kmahar** [comment]
something related to these filters that we will need to think about is how we prevent an email from getting sent back to us again once it is moderated and sent to the user. presumably we will send it with the original headers intact so we may need to add something additional / figure out how to have a rule that overrides the other forwarding rules.

**Comment by karger** [comment]
we need to be sure the updated headers can't be forged so some crypto 
might be needed.

**Comment by kmahar** [comment]
@oliverjd is working on this

**Comment by amyxzhang** [comment]
Closing this issue now. there is a separate issue for the header forging problem.
