### ISSUE TITLE
whitelist, blacklist support

### ISSUE THREAD

**Issue by kmahar** [haystack/murmur#113]
squadbox users should be able to have sender whitelists and blacklists. we'll probably need a new table for this (we could technically use the ForwardingList table but I think that might be confusing.)
we should let people edit these on the web interface. they should also be able to add a sender to either list by clicking a link at the bottom of an email from them that went through moderation.

**Comment by amyxzhang** [comment]
these have mailing list functionalities too so I agree they should be new tables and also new features in Murmur (related to #103) (banning people from a mailing list, whitelisting people on a mailing list so they don't need to be moderated). 

Also I think it would be useful to allow a "timeout" feature, where someone is banned for X number of hours/days - I mentioned that in other issue but also relevant here.

Also we can think about "shadowbanning" - banning people without letting them know. Not sure which way I feel about this.

**Comment by kmahar** [comment]
Yes I think timeout is a good idea. 

For squadbox, I think that a shadow ban may be best... I worry that if we notify every person that gets blocked that they have been blocked, then that might give them more incentive to try to get around the moderation with new email addresses, etc. Maybe we leave this up to the user though; if they have a form/prewritten reply for mods to send then maybe they'd want one of those that gets sent back to harassers instead of the shadow ban. 

For Murmur I'm not so sure. I think someone might be able to catch on kind of easily when their replies are missing from the quoted parts of later replies... I also just don't really like the lack of transparency with it for a group discussion.
