### ISSUE TITLE
Handling when  a user tries to unsubscribe from a mailing list they created

### ISSUE THREAD

**Issue by soyapark** [haystack/murmur#284]
Assigned to @raxelg

Copying from previous Raxel's heuristic evaluation https://github.com/haystack/murmur/issues/283

One possible user flow is 1) if there is another admin, they * can * unsubscribe from the list. 2) if they are the only admin, we should give warning that "if you unsubscribe from the list, it will remove this mailing list".

Before implementation, please suggest mock-up or plans.

**Comment by raxelg** [comment]
@soyapark I agree with the user flow. One case within scenario 1 is when there are more than one admin besides the creator. I'm thinking of opening a dialog box where the creator can select the admin to take his place.

**Comment by soyapark** [comment]
> Update: I will be storing the number of admins in the mailing list in the group_info object passed to the html where I will store the value in a hidden element. 

Why don't you query the number rather than storing the number upfront? What if every other admin already unsubscribe after the user loads this page? Using your algorithm, the stored data will be more than 1, so it will let the user to unsubscribe but it shouldn't or give them warning. Instead, whenever an admin tries to unsubscribe from the group, you can query db to find the current number of admins in this group * on demand *. This way, it will be more up-to-date.

**Comment by raxelg** [comment]
I see what you're saying I will query the db but I also need to confirm that the person unsubscribing is an admin. If the user isn't an admin the condition will create an error where a regular member in a mailing list with only one admin will receive the warning.
