### ISSUE TITLE
Users invited to private mailing list generates error when not subscribed

### ISSUE THREAD

**Issue by raxelg** [haystack/murmur#299]
The following email is an invitation to join a private mailing list. If the user is not subscribed the link focused below will throw the error UnboundLocalError by trying to see the posts of a private group. This issue could generalize to anyone that visits the group via its url (e.g `/posts?group_name={group_name}`). The error should be recognized and inform the user that the mailing list is private so you can't view posts (also adding to subscribe if invitation email was sent or contact the mailing list to be invited to help with next steps). 

<img width="814" alt="Screen Shot 2020-07-15 at 4 57 26 PM" src="https://user-images.githubusercontent.com/39710446/87595810-229c2b00-c6bd-11ea-9896-b6ce664c9aa7.png">

<img width="615" alt="Screen Shot 2020-07-15 at 4 51 15 PM" src="https://user-images.githubusercontent.com/39710446/87595212-3004e580-c6bc-11ea-9dd9-22ca3035bf93.png">

**Comment by soyapark** [comment]
Sorry this happened because the url is murmur.csail.mit.edu not murmur-dev.csail.mit.edu. This happened because I directly copy murmur.csail without any modification. Now it is set properly, so this bug is not happening. Closing the issue
