### ISSUE TITLE
Clean up emails for everyone

### ISSUE THREAD

**Issue by amyxzhang** [haystack/murmur#31]
add subscribe/unsubscribe links to emails. and group page links.

create get endpoints for subscribe/unsubscribe

Have plaintext all be mailto links and make them work (how to do change of settings?)

what other functionality to add to emails?

**Comment by karger** [comment]
another thing we've considered specifically for plain text mail readers 
is the ability to send commands to murmur by email.  e.g. replying to a 
message with one containing "mute" in the first line would cause the 
thread to be muted.

**Comment by amyxzhang** [comment]
Closing this because this issue is too broad and most things mentioned have been completed.
