### ISSUE TITLE
let admins delete users and set users as admins and mods

### ISSUE THREAD

**Issue by amyxzhang** [haystack/murmur#4]
alter jquery datatable so that possible to do mass and one-off deletion and admin/mod setting.

**Comment by amyxzhang** [comment]
Joy is working on this

**Comment by karger** [comment]
You can and should assign issues to people in github.


Sent from phone.  Please excuse typos.-------- Original message --------From: Amy Zhang <notifications@github.com> Date: 10/06/2015  6:57 PM  (GMT-05:00) To: haystack/mailx <mailx@noreply.github.com> Subject: Re: [mailx] let admins delete users and set users as admins and mods
  (#4) 
Joy is working on this

**Comment by amyxzhang** [comment]
I can't assign her or tag her in anything until you add her to the repo for
some reason. her github username is joysyu.

On Tue, Oct 6, 2015 at 7:17 PM, David Karger <notifications@github.com>
wrote:

> You can and should assign issues to people in github.
>
>
> Sent from phone.  Please excuse typos.-------- Original message
> --------From: Amy Zhang <notifications@github.com> Date: 10/06/2015 6:57
> PM (GMT-05:00) To: haystack/mailx <mailx@noreply.github.com> Subject: Re:
> [mailx] let admins delete users and set users as admins and mods
> (#4)
> Joy is working on this
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/mailx/issues/4#issuecomment-146031121>.
>



-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh

**Comment by kmahar** [comment]
On a related note, it would be nice to allow users to become the admin of a group if they are in one without an admin. (I think Facebook gives you this option.) This will happen now in Murmur if the admin of the group leaves - and then the group will forever be stuck with no admin. (Ideally the admin would add a new admin before leaving, but that might not always happen)

**Comment by amyxzhang** [comment]
Closing this as Joy's last pull request has been merged. Yes we need rules requiring admins to set another admin if they are the last one (and are trying to leave the group).
