### ISSUE TITLE
automatically unsubscribe by replying "unsubscribe"

### ISSUE THREAD

**Issue by amyxzhang** [haystack/murmur#51]
to the subscription email or to any thread.

**Comment by karger** [comment]
does this unsubscribe to the whole list or only to the thread?
If only to the thread perhaps mute is a better command?
If to the whole list it seems a too-easy way to (accidentally) take a
drastic action?

**Comment by amyxzhang** [comment]
the whole list. How would someone accidentally do it though? They'd have to reply with "unsubscribe", not click a button or a link (which they can do w.r.t. mute right now).
 
people already do this too so it's not unclear in my opinion (even though it often doesn't work (ever get those email threads with people saying "unsubscribe"? heh.))

**Comment by amyxzhang** [comment]
This was completed by @kmahar
