### ISSUE TITLE
Murmur vs. MailX, what’s actual project’s name?

### ISSUE THREAD

**Issue by jirutka** [haystack/murmur#53]
I’m quite confused, there’s Murmur in some places and MailX on others.

**Comment by amyxzhang** [comment]
Sorry the project was once called mailx and was renamed to murmur. You may
see some discrepancies in a few places still.

On Thursday, November 19, 2015, Jakub Jirutka <notifications@github.com>
wrote:

> I’m quite confused, there’s Murmur in some places and MailX on others.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/murmur/issues/53>.
>


-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh

**Comment by amyxzhang** [comment]
fixed by commit 6f9bb2d898fdcfe8932c25779ce27a607f9b4de8
