### ISSUE TITLE
add some more file formats for attachments

### ISSUE THREAD

**Issue by amyxzhang** [haystack/murmur#77]
xls was requested. maybe we can open the whitelist a little more with some other formats (doc, ppt, etc.)

**Comment by eirikbakke** [comment]
xls is the older Excel format; xlsx is the newer one.

**Comment by kmahar** [comment]
Current whitelist: 

`ALLOWED_MIMETYPES = ["image/jpeg", "image/bmp", "image/gif", "image/png", "application/pdf",    "application/mspowerpoint","application/x-mspowerpoint", "application/powerpoint", "application/vnd.ms-powerpoint", "application/msword", "text/plain"]`

 So I think based on this we support .ppt and .doc. We could add .xls, .xlsx, .pptx, .docx

**Comment by amyxzhang** [comment]
Yes, if there are any others you think would be good, feel free to suggest.

On Wed, Apr 6, 2016 at 11:47 AM, Kaitlin Mahar <notifications@github.com>
wrote:

> Current whitelist:
>
> ALLOWED_MIMETYPES = ["image/jpeg", "image/bmp", "image/gif", "image/png",
> "application/pdf", "application/mspowerpoint","application/x-mspowerpoint",
> "application/powerpoint", "application/vnd.ms-powerpoint",
> "application/msword", "text/plain"]
>
> So I think based on this we support .ppt and .doc. We could add .xls,
> .xlsx, .pptx, .docx
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/murmur/issues/77#issuecomment-206436839>
>



-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh

**Comment by kmahar** [comment]
Polling my friends right now, the only thing they mentioned emailing
frequently that's not on that list is .zip files. I guess that basically
ends up allowing all file types to be emailed though, as they could just be
zipped up... What is the motivation exactly behind having a white list?

**Comment by amyxzhang** [comment]
Fear of people using it send spam/malware or illegal file sharing. We set a
max size of like 2 or 5 MB which helps with second problem. Whitelisting
helps with first problem. yeah idk about zip files. I just don't want users
in our public groups to be targeted. We have no spam or virus detection
software scanning the attachments or anything like that right now and this
is the easy solution.

On Wed, Apr 6, 2016 at 1:10 PM, Kaitlin Mahar <notifications@github.com>
wrote:

> Polling my friends right now, the only thing they mentioned emailing
> frequently that's not on that list is .zip files. I guess that basically
> ends up allowing all file types to be emailed though, as they could just be
> zipped up... What is the motivation exactly behind having a white list?
> On Wed, Apr 6, 2016 at 12:50 PM Amy Zhang <notifications@github.com>
> wrote:
>
> > Yes, if there are any others you think would be good, feel free to
> suggest.
> >
> > On Wed, Apr 6, 2016 at 11:47 AM, Kaitlin Mahar <notifications@github.com
> >
> > wrote:
> >
> > > Current whitelist:
> > >
> > > ALLOWED_MIMETYPES = ["image/jpeg", "image/bmp", "image/gif",
> "image/png",
> > > "application/pdf",
> > "application/mspowerpoint","application/x-mspowerpoint",
> > > "application/powerpoint", "application/vnd.ms-powerpoint",
> > > "application/msword", "text/plain"]
> > >
> > > So I think based on this we support .ppt and .doc. We could add .xls,
> > > .xlsx, .pptx, .docx
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/haystack/murmur/issues/77#issuecomment-206436839>
> > >
> >
> >
> >
> > --
> > Amy X. Zhang | Ph.D. student at MIT CSAIL |
> > http://people.csail.mit.edu/axz
> > | @amyxzh
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/haystack/murmur/issues/77#issuecomment-206461503>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/murmur/issues/77#issuecomment-206468890>
>



-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh
