### ISSUE TITLE
allow admins to set attachment-related settings

### ISSUE THREAD

**Issue by amyxzhang** [haystack/murmur#8]
let admins specify if a group will allow attachments, if yes, maybe what kinds only, and a max size parameter. currently attachments (only images and pdfs) are allowed and max size is hard-coded. no further spam/virus detection yet either.

**Comment by amyxzhang** [comment]
potentially use for virus detection: http://xael.org/norman/python/pyclamd/

**Comment by amyxzhang** [comment]
admins can now set attachments. size set to 1 MB, still only allow images and pdfs.

**Comment by amyxzhang** [comment]
made it so attachments not of the allowed types just don't get attached. Otherwise, done.

**Comment by karger** [comment]
Doesn't seem terrible to have this setting, but is there a case where it will actually be used?  Why would you not let all attachments through?

**Comment by amyxzhang** [comment]
my biggest concern was spam/malware so I went very conservative with my choices.

**Comment by karger** [comment]
so the default is to block attachments?  that seems like a potential
trip-up for naive users who won't want them blocked but don't know how
to unblock them.  Perhaps we need to include a message saying
"attachment blocked; to learn how to unblock click here".

**Comment by amyxzhang** [comment]
by default attachments are allowed actually. but I only allow attachments
of 1 MB and img, jpg, png, pdf, doc and a few other types. And users will
see the setting when they try to make a group:

http://murmur.csail.mit.edu/create_new_group



On Wed, Oct 14, 2015 at 2:16 PM, David Karger <notifications@github.com>
wrote:

> so the default is to block attachments? that seems like a potential
> trip-up for naive users who won't want them blocked but don't know how
> to unblock them. Perhaps we need to include a message saying
> "attachment blocked; to learn how to unblock click here".
>
> On 10/14/2015 2:14 PM, Amy Zhang wrote:
> >
> > my biggest concern was spam/malware so I went very conservative with
> > my choices.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/haystack/murmur/issues/8#issuecomment-148142096>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/murmur/issues/8#issuecomment-148142612>.
>



-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh
