### ISSUE TITLE
Schema/models for Squadbox 

### ISSUE THREAD

**Issue by kmahar** [haystack/murmur#97]
Need to figure out how to best incorporate Murmur data models with what we need for Squadbox

**Comment by amyxzhang** [comment]
After talking with David, we think the best way is to have everything coupled. That is - everything you can do in Squadbox you should be able to do in Murmur and vice versa (with the interface and presentation of the schema such that some things are emphasized in one vs the other). So building out Squadbox is the same as adding moderation powers to Murmur. I would approach schema and logic design with that in mind.

**Comment by kmahar** [comment]
I think this is mostly done minus figuring out how we should store the blacklisted words. I guess just a table with a list of words, and foreign keys to users?

**Comment by amyxzhang** [comment]
my understanding is that there should be a user-to-group whitelist and user-to-group blacklist, in addition to a word/phrase-to-group whitelist and word/phrase-to-group blacklist.

**Comment by kmahar** [comment]
ah, right, they should be associated with the groups. so we have the WhiteOrBlacklist table now that is for user-to-group, and I will add another similar one that is for word/phrase-to-group.
